workflows:
  windows:
    instance_type: windows
    name: Build for Windows
    scripts:
      - name: Install Flutter dependencies
        script: flutter packages pub get
      - name: Build Windows app
        script: flutter build windows
    artifacts:
      - build/windows/runner/Release/*
      - build/windows/runner/Debug/*
  dummy-job:
    instance_type: windows
    name: Dummy CI job
    cache:
      cache_paths:
        - message.txt
    scripts:
      - echo "hello"
      - |
        if (Test-Path .\message.txt) {
            Get-Content .\message.txt
        } else {
            Write-Output 'No message'
        }
        New-Item -Path .\message.txt -ItemType File -Value "Cache from build $env:FCI_BUILD_ID at $(date)" -Force
