workflows:
  windows:
    instance_type: windows
    name: Build for Windows
    scripts:
      - name: Install Flutter dependencies
        script: flutter packages pub get
      - name: Build Android app bundle
        script: flutter build appbundle --build-name=1.0.$env:BUILD_NUMBER --build-number=1.0.$env:BUILD_NUMBER
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
  android:
    instance_type: windows
    name: Build for Android
    scripts:
      - name: Install Flutter dependencies
        script: flutter packages pub get
      - name: Build Windows app
        script: flutter build app-bundle
    artifacts:
      - build/windows/runner/Release/*
      - build/windows/runner/Debug/*
  dummy-job:
    instance_type: windows
    name: Dummy CI job
    cache:
      cache_paths:
#         - $FCI_BUILD_DIR/message.txt
        - $HOME/message.txt
    scripts:
      - echo "hello"
      - |
        $filePath = "$env:HOME\message.txt"
        if (Test-Path "$filePath") {
            Write-Output '>>> Message from the past:'
            Get-Content "$filePath"
        } else {
            Write-Output '>>> No message from the past.'
        }
        New-Item -Path "$filePath" -ItemType File -Value "Cache from build $env:FCI_BUILD_ID at $(date)" -Force
