workflows:
  windows:
    instance_type: windows
    name: Build for Windows
    scripts:
      - name: Install Flutter dependencies
        script: flutter packages pub get
      - name: Build Windows app
        script: flutter build windows
    artifacts:
      - build/windows/runner/Release/*
      - build/windows/runner/Debug/*
  dummy-job:
    instance_type: windows
    name: Dummy CI job
    cache:
      cache_paths:
        - $FCI_BUILD_DIR/message.txt
    scripts:
      - echo "hello"
      - |
        if (Test-Path "$env:FCI_BUILD_DIR\message.txt") {
            Write-Output '>>> Message from the past:'
            Get-Content "$env:FCI_BUILD_DIR\message.txt"
        } else {
            Write-Output '>>> No message from the past.'
        }
        New-Item -Path "$env:FCI_BUILD_DIR\message.txt" -ItemType File -Value "Cache from build $env:FCI_BUILD_ID at $(date)" -Force
